# Generated by Django 2.2.4 on 2020-10-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20201014_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
